### PR TITLE
fix: correctly calculate file lengths on byte streams from paths

### LINKED ISSUE #678: `Path.asByteStream()` calculates incorrect content length unless `endInclusive` is specified
## Describe the bug

When using the extension method `Path.asByteStream()` to get a streaming body, the `endInclusive` parameter must be specified otherwise the content length is incorrectly calculated. The `-1` default is passed through to the `File.asByteStream()` method which in turn passes it to `FileContent` where its meaning is lost, leading to content lengths of 0 bytes.

This causes streaming bodies to have incorrect lengths calculated leading to errors like:

```
Exception in thread "main" java.net.ProtocolException: expected 0 bytes but received 8192
	at okhttp3.internal.connection.Exchange$RequestBodySink.write(Exchange.kt:219)
	at okio.RealBufferedSink.emitCompleteSegments(RealBufferedSink.kt:255)
	at okio.RealBufferedSink.write(RealBufferedSink.kt:88)
	at aws.smithy.kotlin.runtime.http.engine.okhttp.ByteChannelRequestBody$writeTo$1.invokeSuspend(ByteChannelRequestBody.kt:51)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.EventLoopImplBase.processNextEvent(EventLoop.common.kt:284)
	at kotlinx.coroutines.BlockingCoroutine.joinBlocking(Builders.kt:85)
	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking(Builders.kt:59)
	at kotlinx.coroutines.BuildersKt.runBlocking(Unknown Source)
	at aws.smithy.kotlin.runtime.http.engine.okhttp.ByteChannelRequestBody.writeTo(ByteChannelRequestBody.kt:41)
	at okhttp3.internal.http.CallServerInterceptor.intercept(CallServerInterceptor.kt:62)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
	at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.kt:34)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
	at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.kt:95)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
	at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.kt:84)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
	at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.kt:65)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
	at okhttp3.internal.connection.RealCall.getResponseWithInterceptorChain$okhttp(RealCall.kt:205)
	at okhttp3.internal.connection.RealCall$AsyncCall.run(RealCall.kt:533)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

## Expected Behavior

`Path.asByteStream()` should work properly even with no `endInclusive` parameter specified.

### PR DESCRIPTION
**Pull request by ianbotsf**
## Issue \#

Closes #678 

## Description of changes

We were calculating `endInclusive` incorrectly downstream of `Path.asByteStream` when no explicit value was passed. This change explicitly calculates file length if none is provided and prohibits `endInclusive == -1` in `File.asByteStream`.

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

File: runtime/runtime-core/jvm/src/aws/smithy/kotlin/runtime/content/ByteStreamJVM.kt [hunk 1]
```diff
@@ -45,7 +45,14 @@ public fun Path.asByteStream(start: Long = 0, endInclusive: Long = -1): ByteStre
     val f = toFile()
     require(f.exists()) { "cannot create ByteStream, file does not exist: $this" }
     require(f.isFile) { "cannot create a ByteStream from a directory: $this" }
-    return f.asByteStream(start, endInclusive)
+
+    val calculatedEndInclusive = when {
+        endInclusive >= 0L -> endInclusive
+        endInclusive == -1L -> f.length() - 1
+        else -> throw IllegalArgumentException("endInclusive must be -1 or greater")
```
Comment (aajtodd) [inline runtime/runtime-core/jvm/src/aws/smithy/kotlin/runtime/content/ByteStreamJVM.kt:52]: style/nit: `error(...)`

**Review by aajtodd — APPROVED** [review]

File: runtime/runtime-core/jvm/src/aws/smithy/kotlin/runtime/content/ByteStreamJVM.kt (hunk 1 above)
Comment (aajtodd) [reply runtime/runtime-core/jvm/src/aws/smithy/kotlin/runtime/content/ByteStreamJVM.kt:52]: err yes `require` I guess is what I meant, this isn't that big of deal you can leave it as is

**Review by lucix-aws — APPROVED** [review]
