### PR TITLE
fix: correct URL encoding in endpoint resolution

### LINKED ISSUE #888: Resolved endpoint URLs are incorrectly decoded
## Describe the bug
The endpoint provider generator [calls `Url.parse`](https://github.com/awslabs/smithy-kotlin/blob/3e1d8618b0090b218461cffdcce20619d6b4119b/codegen/smithy-kotlin-codegen/src/main/kotlin/software/amazon/smithy/kotlin/codegen/rendering/endpoints/DefaultEndpointProviderGenerator.kt#L149) on constructed URLs. `Url.parse` [delegates to `urlParseImpl`](https://github.com/awslabs/smithy-kotlin/blob/3e1d8618b0090b218461cffdcce20619d6b4119b/runtime/runtime-core/common/src/aws/smithy/kotlin/runtime/net/Url.kt#L42), which [URL-decodes path components](https://github.com/awslabs/smithy-kotlin/blob/3e1d8618b0090b218461cffdcce20619d6b4119b/runtime/runtime-core/common/src/aws/smithy/kotlin/runtime/net/UrlParser.kt#L28). This leads to incorrectly decoding values which have already been URL-_encoded_ by the `uriEncode` built-in endpoint function.

## Expected Behavior
URL-encoded path components generated by endpoint providers should not be decoded when constructing a `Url`.

### PR DESCRIPTION
**Pull request by ianbotsf**
## Issue \#

Closes #888 

## Description of changes

This change corrects a bug in URL encoding in endpoint resolution which caused parsing to URL-_decode_ strings which were already properly encoded.

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Review by lucix-aws — APPROVED** [review]

File: runtime/runtime-core/common/src/aws/smithy/kotlin/runtime/net/UrlParser.kt [hunk 1]
```diff
@@ -25,20 +25,20 @@ internal fun urlParseImpl(url: String): Url =
...
-                path = "/${it.urlDecodeComponent()}"
+                path = "/${decodingBehavior.maybeDecode(it)}"
             }
         }
 
         if (next.startsWith("?")) {
             next = next.capture(1 until next.firstIndexOrEnd("#")) {
                 it.splitAsQueryString().entries.forEach { (k, v) ->
-                    parameters.appendAll(k.urlDecodeComponent(), v.map(String::urlDecodeComponent))
+                    parameters.appendAll(decodingBehavior.maybeDecode(k), v.map { decodingBehavior.maybeDecode(it) })
```
Comment (lucix-aws) [inline runtime/runtime-core/common/src/aws/smithy/kotlin/runtime/net/UrlParser.kt:35]: Question: Do we want this decode/no-decode to be a blanket setting?

The reason for shutting it off on the path is clear - but it seems like you'd always want the query decoded (and it would always be safe to do so).

Comment (ianbotsf) [reply runtime/runtime-core/common/src/aws/smithy/kotlin/runtime/net/UrlParser.kt:35]: Yeah you're probably right. Will revise.

File: runtime/runtime-core/common/src/aws/smithy/kotlin/runtime/net/UrlParser.kt [hunk 2]
```diff
@@ -23,16 +24,20 @@ internal fun urlParseImpl(url: String): Url =
...
-                path = "/${it.urlDecodeComponent()}"
+                path = "/${pathDecode(it)}"
             }
         }
 
         if (next.startsWith("?")) {
             next = next.capture(1 until next.firstIndexOrEnd("#")) {
                 it.splitAsQueryString().entries.forEach { (k, v) ->
-                    parameters.appendAll(k.urlDecodeComponent(), v.map(String::urlDecodeComponent))
+                    parameters.appendAll(k.urlEncodeComponent(), v.map(String::urlDecodeComponent))
```
Comment (aajtodd) [inline runtime/runtime-core/common/src/aws/smithy/kotlin/runtime/net/UrlParser.kt:40]: **correctness**: Why are we now encoding the key?

File: runtime/runtime-core/common/src/aws/smithy/kotlin/runtime/net/Url.kt [hunk 3]
```diff
@@ -104,6 +105,21 @@ private fun encodePath(
  */
 public data class UserInfo(public val username: String, public val password: String)
 
+/**
+ * Identifies the type of decoding behavior desired when parsing a URL.
+ */
+public enum class UrlDecodingBehavior {
```
Comment (aajtodd) [inline runtime/runtime-core/common/src/aws/smithy/kotlin/runtime/net/Url.kt:111]: **comment**: This has odd semantics since component may be from path or query parameters. Only path decoding consults this enum in the parse implementation which sort of reaffirms the oddness of it.

File: runtime/runtime-core/common/src/aws/smithy/kotlin/runtime/net/Url.kt [hunk 4]
```diff
@@ -104,6 +105,21 @@ private fun encodePath(
...
+    /**
+     * Identifies that a URL string does not its path component need to be URL-decoded.
```
Comment (aajtodd) [inline runtime/runtime-core/common/src/aws/smithy/kotlin/runtime/net/Url.kt:113]: **nit**: 

> Identifies that a URL string does not **need** its path component need to be URL-decoded.

File: runtime/runtime-core/common/src/aws/smithy/kotlin/runtime/net/UrlParser.kt (hunk 2 above)
Comment (ianbotsf) [reply runtime/runtime-core/common/src/aws/smithy/kotlin/runtime/net/UrlParser.kt:40]: 😳 That's an accidental change. Will fix.

**Review by aajtodd — APPROVED** [review]
