### PR TITLE
fix: correctly sign special characters (e.g., "@") in URL paths

### LINKED ISSUE #1008: Invalid signatures due to URL encoding changes (0.36.1-beta vs 1.0.0+)
## Describe the bug

When using `ApiGatewayManagementClient` (AWS Kotlin SDK 1.0.0 or higher) to send a message on an API GW Websocket calls to `ApiGatewayManagementClient.postToConnection` now fail with a `InvalidSignatureException` due to a signature validation error.

This exception did not occur with v0.36.1-beta or previous versions.

This appears to be related to the URL encoding changes, specifically the canonicalization of a Url [here](https://github.com/awslabs/smithy-kotlin/blob/8460072eb51aa5e6db73224cf0f125c014f2ea98/runtime/auth/aws-signing-default/common/src/aws/smithy/kotlin/runtime/auth/awssigning/Canonicalizer.kt#L194).  A quick review of that code allows `@` as a valid (hence unescaped) character, whereas it was previously escaped, with the endpoint expecting it to be escaped.

Walking through both SDK versions with a debugger we end up with a string-to-sign (fragment) of:

* `0.36.1-beta` (works): `/%40connections/PiJ_BfnLoAMCJEw%253D`
* `1.0.0+` (fails): `/@connections/PiJ_BfnLoAMCJEw%253D`

Note the failing version does not escape `@` as noted earlier.

While this specific issue pertains to API GW WS SDK calls it's likely there are other areas that are similarly affected given the convergence of signing / canonicalization.  Any SDK call with `@` in the path will fail to generate the correct canonical string; there may be other characters likewise affected.

## Expected Behavior

SDK calls generate a proper, valid signature, as expected and validated by AWS endpoints.

## Current Behavior

The noted SDK call generates an invalid signature and is rejected by the AWS endpoint.

The full exception (sensitive portions redacted):
```
Exception in thread "main" aws.sdk.kotlin.services.apigatewaymanagementapi.model.ApiGatewayManagementException: The request signature we calculated does not match the signature you provided. Check your AWS Secret Access Key and signing method. Consult the service documentation for details.

The Canonical String for this request should have been
'POST
/%40connections/PiJ_BfnLoAMCJEw%253D

amz-sdk-invocation-id:<redcated>
amz-sdk-request:attempt=1; max=3
content-type:application/octet-stream
host:<redacted>
x-amz-date:20231206T200102Z
x-amz-security-token:<redacted>
x-amz-user-agent:aws-sdk-kotlin/1.0.10

amz-sdk-invocation-id;amz-sdk-request;content-type;host;x-amz-date;x-amz-security-token;x-amz-user-agent
7aa80cee51dcb3ca48c9f0af0a4b30a6ebdcf5bfdcca57352c6dfe7bb96cf64d'

The String-to-Sign should have been
'AWS4-HMAC-SHA256
20231206T200102Z
20231206/us-east-1/execute-api/aws4_request
ee606f6d4ade53ffc098d07d92eb55db183510cbcd6662c08669c6cc211c8027'

	at aws.sdk.kotlin.services.apigatewaymanagementapi.serde.PostToConnectionOperationDeserializerKt.throwPostToConnectionError(PostToConnectionOperationDeserializer.kt:49)
	at aws.sdk.kotlin.services.apigatewaymanagementapi.serde.PostToConnectionOperationDeserializerKt.access$throwPostToConnectionError(PostToConnectionOperationDeserializer.kt:1)
	at aws.sdk.kotlin.services.apigatewaymanagementapi.serde.PostToConnectionOperationDeserializerKt$throwPostToConnectionError$1.invokeSuspend(PostToConnectionOperationDeserializer.kt)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.internal.DispatchedContinuationKt.resumeCancellableWith(DispatchedContinuation.kt:283)
	at kotlinx.coroutines.internal.DispatchedContinuationKt.resumeCancellableWith$default(DispatchedContinuation.kt:278)
	at kotlinx.coroutines.DispatchedCoroutine.afterResume(Builders.common.kt:261)
	at kotlinx.coroutines.AbstractCoroutine.resumeWith(AbstractCoroutine.kt:102)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:108)
	at kotlinx.coroutines.internal.LimitedDispatcher$Worker.run(LimitedDispatcher.kt:115)
	at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:103)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:584)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:793)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:697)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:684)
```

## Steps to Reproduce

A reproducer can be made available if need be; the above information should be enough to craft unit tests to validate issues with canonicalization.

## Possible Solution

n/a

## Context

This issue affects the SDK 1.0.0+ and prevents use of SDK calls that incorrectly sign the request.  At the moment, for our use cases, it is limited to AWS API GW Websocket 'post to connection' calls.

Any SDK calls that have `@` in the URL path may also be affected in a similar manner; the issue may extend beyond just the failure to escape `@` and include other characters that invalidate the signature.

## Your Environment

* Smithy Kotlin version used: 0.36.1-beta works; 1.0.0+ (incl. 1.0.10) fail as noted above
* Platform (JVM/JS/Native): JVM
* Operating System and version: MacOS & Linux

### PR DESCRIPTION
**Pull request by ianbotsf**
## Issue \#

Closes #1008 

## Description of changes

This update fixes encoding and signing problems around special characters in URL paths and query parameters. The root of the problem is that some characters (e.g., `@`) are valid in paths and queries according to [RFC 3986](https://datatracker.ietf.org/doc/html/rfc3986) but are [required to be escaped for the purposes of URL signing](https://docs.aws.amazon.com/IAM/latest/UserGuide/create-signed-request.html#create-canonical-request). Prior code didn't properly differentiate the character sets that must be escaped in both situations and instead treated them as identical.

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

File: runtime/runtime-core/common/src/aws/smithy/kotlin/runtime/text/encoding/PercentEncoding.kt [hunk 1]
```diff
@@ -66,15 +68,21 @@ public class PercentEncoding(
         public val Fragment: Encoding = PercentEncoding("fragment", VALID_FCHAR)
 
         /**
-         * A [PercentEncoding] instance suitable for encoding `application/x-www-form-urlencoded` data
+         * A [PercentEncoding] instance suitable for encoding Smithy-specific `application/x-www-form-urlencoded` data
          */
-        public val FormUrl: Encoding = PercentEncoding("form URL", VALID_QCHAR, mapOf(' ' to '+'))
```
Comment (aajtodd) [inline runtime/runtime-core/common/src/aws/smithy/kotlin/runtime/text/encoding/PercentEncoding.kt:71]: **correctness**: Shouldn't form url encoding map spaces to `+`?

File: runtime/runtime-core/common/test/aws/smithy/kotlin/runtime/net/url/QueryParametersTest.kt [hunk 2]
```diff
@@ -22,25 +22,25 @@ class QueryParametersTest {
     fun testDecodedParametersAlternateEncoding() {
         val paramString = QueryParameters {
             decodedParameters {
-                add("a", "green apple")
```
Comment (aajtodd) [inline runtime/runtime-core/common/test/aws/smithy/kotlin/runtime/net/url/QueryParametersTest.kt:25]: Should we not retain testing for space handling difference as well as `:`?

File: runtime/auth/aws-signing-default/common/src/aws/smithy/kotlin/runtime/auth/awssigning/Canonicalizer.kt [hunk 3]
```diff
@@ -193,10 +203,13 @@ private const val STREAM_CHUNK_BYTES = 16384 // 16KB
  */
 internal fun Url.Builder.canonicalPath(config: AwsSigningConfig): String {
     val srcPath = path
-    val srcSegments = srcPath.encodedSegments
-    val destSegments = if (config.useDoubleUriEncode) srcSegments.map(PercentEncoding.Path::encode) else srcSegments
+    val srcSegments = srcPath.segments
+    val mapper: (Encodable) -> Encodable = when (config.useDoubleUriEncode) {
+        true -> { existing -> PercentEncoding.SigV4.encodableFromDecoded(existing.encoded) }
```
Comment (aajtodd) [inline runtime/auth/aws-signing-default/common/src/aws/smithy/kotlin/runtime/auth/awssigning/Canonicalizer.kt:208]: **correctness**: You're calling `encodableFromDecoded` but passing `existing.encoded`?

**Review by lauzadis — APPROVED** [review]

File: runtime/auth/aws-signing-default/common/src/aws/smithy/kotlin/runtime/auth/awssigning/Canonicalizer.kt (hunk 3 above)
Comment (aajtodd) [reply runtime/auth/aws-signing-default/common/src/aws/smithy/kotlin/runtime/auth/awssigning/Canonicalizer.kt:208]: Ahh right because it's supposed to be double URI encoded?

File: runtime/runtime-core/common/test/aws/smithy/kotlin/runtime/net/url/QueryParametersTest.kt (hunk 2 above)
Comment (ianbotsf) [reply runtime/runtime-core/common/test/aws/smithy/kotlin/runtime/net/url/QueryParametersTest.kt:25]: Can do!

File: runtime/auth/aws-signing-default/common/src/aws/smithy/kotlin/runtime/auth/awssigning/Canonicalizer.kt (hunk 3 above)
Comment (ianbotsf) [reply runtime/auth/aws-signing-default/common/src/aws/smithy/kotlin/runtime/auth/awssigning/Canonicalizer.kt:208]: Exactly, this is the double-encoding case. I'll add a comment to make it clearer but this is definitely correct behavior according to all the tests/specs.

**Review by aajtodd — APPROVED** [review]
